NAME = libft.a

BSDIR = basic_src/

PFDIR = printf_src/

SRC =	$(BSDIR)ft_putchar.c \
		$(BSDIR)ft_putstr.c \
		$(BSDIR)ft_putendl.c \
		$(BSDIR)ft_putnbr.c \
		$(BSDIR)ft_putchar_fd.c \
		$(BSDIR)ft_putstr_fd.c \
		$(BSDIR)ft_putendl_fd.c \
		$(BSDIR)ft_putnbr_fd.c \
		$(BSDIR)ft_strlen.c \
		$(BSDIR)ft_strcpy.c \
		$(BSDIR)ft_strncpy.c \
		$(BSDIR)ft_strcat.c \
		$(BSDIR)ft_strncat.c \
		$(BSDIR)ft_strchr.c \
		$(BSDIR)ft_strrchr.c \
		$(BSDIR)ft_strstr.c \
		$(BSDIR)ft_strnstr.c \
		$(BSDIR)ft_isalpha.c \
		$(BSDIR)ft_isdigit.c \
		$(BSDIR)ft_isalnum.c \
		$(BSDIR)ft_isprint.c \
		$(BSDIR)ft_toupper.c \
		$(BSDIR)ft_tolower.c \
		$(BSDIR)ft_memalloc.c \
		$(BSDIR)ft_memdel.c \
		$(BSDIR)ft_isascii.c \
		$(BSDIR)ft_strnew.c \
		$(BSDIR)ft_strdel.c \
		$(BSDIR)ft_strclr.c \
		$(BSDIR)ft_striter.c \
		$(BSDIR)ft_striteri.c \
		$(BSDIR)ft_strmap.c \
		$(BSDIR)ft_strmapi.c \
		$(BSDIR)ft_strequ.c \
		$(BSDIR)ft_strnequ.c \
		$(BSDIR)ft_strsub.c \
		$(BSDIR)ft_strjoin.c \
		$(BSDIR)ft_strtrim.c \
		$(BSDIR)ft_strsplit.c \
		$(BSDIR)ft_atoi.c \
		$(BSDIR)ft_ctoa.c \
		$(BSDIR)ft_itoa.c \
		$(BSDIR)ft_itoa_mod.c \
		$(BSDIR)ft_itoa_mod2.c \
		$(BSDIR)ft_itoa_mod3.c \
		$(BSDIR)ft_ftoa.c \
		$(BSDIR)ft_lftoa.c \
		$(BSDIR)ft_strdup.c \
		$(BSDIR)ft_strcmp.c \
		$(BSDIR)ft_strncmp.c \
		$(BSDIR)ft_memset.c \
		$(BSDIR)ft_bzero.c \
		$(BSDIR)ft_memcpy.c \
		$(BSDIR)ft_memccpy.c \
		$(BSDIR)ft_memmove.c \
		$(BSDIR)ft_memchr.c \
		$(BSDIR)ft_strlcat.c \
		$(BSDIR)ft_memcmp.c \
		$(BSDIR)ft_lstnew.c \
		$(BSDIR)ft_lstdelone.c \
		$(BSDIR)ft_lstdel.c \
		$(BSDIR)ft_lstadd.c \
		$(BSDIR)ft_lstiter.c \
		$(BSDIR)ft_lstmap.c \
		$(BSDIR)ft_puterror.c \
		$(BSDIR)get_next_line.c \
		$(BSDIR)ft_itoa_base.c \
		$(BSDIR)ft_itoa_base_mod.c \
		$(BSDIR)ft_upstr.c \
		$(BSDIR)ft_pow.c \
		$(PFDIR)ft_get_var.c \
		$(PFDIR)ft_get_options.c \
		$(PFDIR)ft_get_len_modif.c \
		$(PFDIR)ft_printf.c \
		$(PFDIR)ft_check_var.c \
		$(PFDIR)ft_check_value.c \
		$(PFDIR)ft_saveret.c \
		$(PFDIR)ft_get_value.c \
		$(PFDIR)ft_create_str.c \
		$(PFDIR)ft_apply_options.c \
		$(PFDIR)ft_wchar.c \
		$(PFDIR)ft_wstoa.c \
		$(PFDIR)ft_masks.c \
		$(PFDIR)ft_strdup_mod.c

OBJ =	ft_putchar.o \
		ft_putstr.o \
		ft_putendl.o \
		ft_putnbr.o \
		ft_putchar_fd.o \
		ft_putstr_fd.o \
		ft_putendl_fd.o \
		ft_putnbr_fd.o \
		ft_strlen.o \
		ft_strcpy.o \
		ft_strncpy.o \
		ft_strcat.o \
		ft_strncat.o \
		ft_strchr.o \
		ft_strrchr.o \
		ft_strstr.o \
		ft_strnstr.o \
		ft_isalpha.o \
		ft_isdigit.o \
		ft_isalnum.o \
		ft_isprint.o \
		ft_toupper.o \
		ft_tolower.o \
		ft_memalloc.o \
		ft_memdel.o \
		ft_isascii.o \
		ft_strnew.o \
		ft_strdel.o \
		ft_strclr.o \
		ft_striter.o \
		ft_striteri.o \
		ft_strmap.o \
		ft_strmapi.o \
		ft_strequ.o \
		ft_strnequ.o \
		ft_strsub.o \
		ft_strjoin.o \
		ft_strtrim.o \
		ft_strsplit.o \
		ft_atoi.o \
		ft_ctoa.o \
		ft_itoa.o \
		ft_itoa_mod.o \
		ft_itoa_mod2.o \
		ft_itoa_mod3.o \
		ft_ftoa.o \
		ft_lftoa.o \
		ft_strdup.o \
		ft_strcmp.o \
		ft_strncmp.o \
		ft_memset.o \
		ft_bzero.o \
		ft_memcpy.o \
		ft_memccpy.o \
		ft_memmove.o \
		ft_memchr.o \
		ft_strlcat.o \
		ft_memcmp.o \
		ft_lstnew.o \
		ft_lstdelone.o \
		ft_lstdel.o \
		ft_lstadd.o \
		ft_lstiter.o \
		ft_lstmap.o \
		ft_puterror.o \
		get_next_line.o \
		ft_itoa_base.o \
		ft_itoa_base_mod.o \
		ft_upstr.o \
		ft_pow.o \
		ft_get_var.o \
		ft_get_options.o \
		ft_get_len_modif.o \
		ft_printf.o \
		ft_check_var.o \
		ft_check_value.o \
		ft_saveret.o \
		ft_get_value.o \
		ft_create_str.o \
		ft_apply_options.o \
		ft_wchar.o \
		ft_wstoa.o \
		ft_masks.o \
		ft_strdup_mod.o

HEAD = libft.h

CFLAGS = -Wall -Wextra -Werror

CC = gcc

all: $(NAME)

$(NAME): $(OBJ)
	@echo "				Compiled with succes !!"
	@ar rc $(NAME) $(OBJ)
	@ranlib $(NAME)
	@echo "				Libftprintf created and listed"
$(OBJ):
	@$(CC) $(CFLAGS) -c $(SRC)
clean:
	@/bin/rm -f $(OBJ)
	@echo "				All .o deleted"
fclean: clean
	@/bin/rm -f $(NAME)
	@echo "				Libft deleted"
re: fclean all

.PHONY: all clean fclean re